[package]
name = "packet"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "packet"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.23.0"
interledger-packet = "0.4.0"
hex = "0.4.0"
chrono = "0.4.9"
bytes = "0.4.12"
