name: notify

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.chat }} # user id or channel name secret
          token: ${{ secrets.token }} # token secret
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}